### ISSUE TITLE
World Map

### ISSUE THREAD

**Issue by bates64** [liam4/slw#12]
We need an overworld and level selector - this should make other features trivial e.g. the death zone sends one back to map.

**Comment by bates64** [comment]
Obviously this will need it's own tileset/map.

**Comment by bates64** [comment]
[These](http://mfgg.net/index.php?act=resdb&param=02&c=1&id=30029) [tilesets](http://mfgg.net/index.php?act=resdb&param=02&c=1&id=30322) [look](http://mfgg.net/index.php?act=resdb&param=03&c=1&id=30350) [great](http://mfgg.net/index.php?act=resdb&param=02&c=1&id=30360). We'll probably have to change some colours to fit with each world.

![image](https://cloud.githubusercontent.com/assets/9429556/20013061/b1dd7148-a2a9-11e6-88c9-ee798ff50976.png)

**Comment by bates64** [comment]
Blocked by #17.

**Comment by bates64** [comment]
12a823a271bc9ad162cfb073ce81c8defbbcde4f added levels and paths, but they're not totally complete. We also need to finish physics for the map movement.

![image](https://cloud.githubusercontent.com/assets/9429556/20016429/586015ae-a2b7-11e6-805d-8db0b2398b9b.png)

**You currently can't actually begin levels.**

**Comment by towerofnix** [comment]
Looking great so far!

Moving east on that T-turn is hard though.

**Comment by bates64** [comment]
Agreed.. I think we'll have to come up with some other form of movement on world maps.

**Comment by towerofnix** [comment]
NSMB-style?

(I haven't played past the first level in Super Mario World to know how the world map works there)

**Comment by bates64** [comment]
I guess so (same in SMW as NSMB).

_gitter?_

**Comment by towerofnix** [comment]
I'm pretty sure it should wait until no key is pressed before checking for another key to move the sprite along a world map path – ATM I have to very quickly tap down or up at a T-intersection to get in the middle:

![T-intersection](https://cloud.githubusercontent.com/assets/9948030/20025864/b57cf90e-a2d1-11e6-8b5b-706190ef2073.png)

**Comment by bates64** [comment]
@liam4 hmm, I like that behaviour. We should slow down the map movement instead, the player has a velocity of 16 or 0 in map mode, so we need to animate it..

**Comment by bates64** [comment]
![image](https://cloud.githubusercontent.com/assets/9429556/20029607/4dcf82aa-a348-11e6-90e5-b44c9873003c.png)

We've now got graphics, all we need now is to animate path movement a little smoother.

**Comment by bates64** [comment]
@liam4 go do that ^

**Comment by nanalan** [comment]
Completed in 8839000f20cd1a81e97e3a1a1c7d80a7eb9707d2

**Comment by towerofnix** [comment]
Relevant commits because we didn't link them:

(alex) https://github.com/liam4/slw/commit/15c34f05e7b9ff818ac1605575318bfdf9eec0b8
(alex) https://github.com/liam4/slw/commit/12a823a271bc9ad162cfb073ce81c8defbbcde4f
(alex) https://github.com/liam4/slw/commit/baf19c1cc3483e760640429b31d97b349be186ac
(alex) https://github.com/liam4/slw/commit/63a9dce778857cf0245e1c0f546776291f9d1937
(alex) https://github.com/liam4/slw/commit/3e12a2d8acf6e470303cb29fee1170babe7be1ac
(alex) https://github.com/liam4/slw/commit/3798d4911fb975a2c29d351c6000cae2a5cbeb15, https://github.com/liam4/slw/commit/34e94ff6ec5e27f4e29629206af9bea9be6e6ee4
(alex) https://github.com/liam4/slw/commit/1af973845121edb0af795a5b053293e5e47fea49
(liam) https://github.com/liam4/slw/commit/4f65a1b832165caa7263193caed88898ce365ee7
(liam) https://github.com/liam4/slw/commit/d248551ab14f467735b54581ddd5f9440035d24e
(liam) https://github.com/liam4/slw/commit/fd220de34e7b3fa608c476200c2f91647ab9c85c

@nanalan the one commit you linked doesn't have _anything_ to do with the world map :P

**Comment by bates64** [comment]
Derp :package:
That was the parent commit.
